language: csharp
solution: ds3_net_sdk.sln
script:
  - xbuild /p:Configuration=Release ds3_net_sdk.sln
  - mono ./packages/NUnit.Runners.2.6.3/tools/nunit-console.exe ./TestDs3/bin/Release/TestDs3.dll
